version: '3.3'
services:
  gateway: 
    image: nginx:latest
    container_name: gateway
    restart: always
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      # - 443:443
    networks: 
      - blinkas_net

  blinkas:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: blinkas
    entrypoint: npm start
    volumes:
      - ./src:/app/src
    expose:
      - "3000"
    networks: 
      - blinkas_net

networks: 
  blinkas_net:
